-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Muistiinpano CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;
DROP TABLE IF EXISTS Liitostaulu CASCADE;
